export const  USER_REQUEST = "USER_REQUEST"
export const USER_SUCCESS = "USER_SUCCESS"
export const USER_FAIL = "USER_FAIL"
export const LOAD_USER = "LOAD_USER"
export const UPDATE_LOADER = "UPDATE_LOADER"